version: '3.6'
name: lab46-redirector
services:
  service:
    build: .
    image: lab46-redirector
    container_name: lab46-redirector
    restart: always
    ports:
      - 4500:80
    env_file:
      - .env
    environment:
      - PORT=80
